server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # ???????
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.168.115:3306/login-service?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
  #redis
  redis:
    host: 192.168.121.121
    port: 6379
    password: redis2022
    timeout: 3000
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  jpa:
    show-sql: true # 默认false，在日志里显示执行的sql语句
    database: mysql
    hibernate.ddl-auto: update #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会 新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect # 使用JPA创建表时，默认使用的存储引擎是MyISAM，通过指定数据库版本，可以使用InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    com.hime: info
    org.springframework: error
  config: classpath:logback-spring.xml
logback:
  path: D:\others\logs

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcd1234efgh
  # 令牌有效期（默认30分钟）
  expireTime: 30

