server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # ???????
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.168.115:3306/login-service?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true # ??false??????????sql??
    database: mysql
    hibernate.ddl-auto: update #???update?????????????????????????????? ???????create??????????????????????
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect # ??JPA???????????????MyISAM???????????????InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        #??jpa?????????????????????
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    com.hime: info
    org.springframework: error
  config: classpath:logback-spring.xml
logback:
  path: /opt/login-service/log